In [1]:
import numpy as np
import math

In [2]:
def sort(a):
    sorted_a = a
    n = a.size
    for i in range(0,n):
        for j in range(0,n):
            if sorted_a[j]<sorted_a[i]:
                temp = sorted_a[j]
                sorted_a[j]=sorted_a[i]
                sorted_a[i] = temp
    print(sorted_a)
    return sorted_a

In [3]:
def median(a):
    sorted_a = sort(a)
    mid_index = math.ceil(len(a)/2)-1
    #print(mid_index)
    median_a = sorted_a[mid_index]
    return median_a

In [4]:
def mode(a):
    # assumption: if same max repetation is there. highest mode will be returned
    sorted_a = sort(a)
    #take first value as mode
    mode_a = sorted_a[0]
    #corresponding count to mode value
    max_count = 1
    count = 1
    
    for i in range(1,len(sorted_a)):
        #print(sorted_a[i])
        if sorted_a[i] == sorted_a[i-1]:
            count += 1 
        if count > max_count:
            #print(count)
            max_count = count
            mode_a = sorted_a[i]
        if sorted_a[i] != sorted_a[i-1]:
            count = 1
            
    return mode_a

In [5]:
a = np.random.randint(20, size=21)
a

array([11,  0,  4, 10,  0, 11, 17, 16,  1, 19, 16,  4,  2, 18,  7, 11,  1,
       11, 10, 15, 12])

In [6]:
sum = 0
for i in range(0,a.size):
    sum += a[i]

In [7]:
len_a = len(a)

In [8]:
mean_a = sum/len_a

In [9]:
median_a = median(a) 

[19 18 17 16 16 15 12 11 11 11 11 10 10  7  4  4  2  1  1  0  0]


In [10]:
mode_a = mode(a)

[19 18 17 16 16 15 12 11 11 11 11 10 10  7  4  4  2  1  1  0  0]


In [11]:
print("mean: ", mean_a, " median:", median_a, " mode:",mode_a)

mean:  9.333333333333334  median: 11  mode: 11
