In [29]:
import numpy as np


def read_txt(file_name):
    matrix = []
    f = open(file_name, 'r')
    a = f.read().split('\n')
    # print(a)
    for row in range(0, len(a)-2):
        raw_items = a[row].split(',')
        matrix.append(raw_items)
        # print(matrix)
    matrix = np.asarray(matrix)
    matrix = matrix.astype(int)
    print(matrix)

    return matrix


def read_csv(file_name):
    1 == 1


def solve_lower(matrix, Y):
    N = matrix.shape[0]
    X = []

    for row in range(0, N):
        sum_ = 0
        for col in range(0, row):
            sum_ += matrix[row][col] * X[col]
        X.append((Y[row] - sum_)/matrix[row][row])

    print("Solution: ", X)


def solve_upper(matrix, Y):
    N = matrix.shape[0]
    X = np.zeros(N)

    for row in range(N-1, -1, -1):
        # print(row)
        # continue
        sum_ = 0
        for col in range(N-1, row, -1):
            sum_ += matrix[row][col] * X[col]
        X[row] = (Y[row] - sum_)/matrix[row][row]

    print("Solution: ", X)


def check_triangularity(matrix):
    lower_flag = True
    upper_flag = True
    for row_index, row in enumerate(matrix):
        # print(row)
        for column_index, item in enumerate(row):
            # check for lower-triangal matrix
            if row_index < column_index:
                if item != 0:
                    lower_flag = False

            if row_index > column_index:
                if item != 0:
                    upper_flag = False

    if lower_flag:
        print("matrix type: Lower")
        return 'lower'
        # solve_lower(matrix)

    if upper_flag:
        print("matrix type: Upper")
        return 'upper'
        # solve_upper

    if lower_flag and upper_flag:
        print("matrix type: Diagonal")
        return 'diagonal'


matrix = read_txt("./demofile.txt")
shape = matrix.shape
if shape[0] != shape[1]:
    print("Not square")
    exit()

matrix_type = check_triangularity(matrix)

np.random.seed(0)
Y = np.random.randint(20, size=shape[1])


if matrix_type == 'lower':
    solve_lower(matrix, Y)

if matrix_type == 'upper':
    solve_upper(matrix, Y)


[[2 0 0 0 0]
 [2 3 0 0 0]
 [1 2 3 0 0]
 [3 4 5 6 0]
 [3 4 5 6 7]]
matrix type: Lower
Solution:  [6.0, 1.0, -2.6666666666666665, -0.9444444444444446, 0.0]
