In [3]:
import numpy as np

def read_txt(file_name):
    matrix = []
    f = open(file_name, 'r')
    a = f.read().split('\n')
    print(a)
    for row in range(0,len(a)-2):
        raw_items = a[row].split(',')
        matrix.append(raw_items)
        #print(matrix)
    matrix = np.asarray(matrix)
    matrix = matrix.astype(int)
    print(matrix)
    
    return matrix

def read_csv(file_name):
    1==1
    
def check_triangularity(matrix):
    lower_flag = True
    upper_flag = True
    for row_index,row in enumerate(matrix):
        print(row)
        for column_index,item in enumerate(row):
            #check for lower-triangal matrix
            if row_index<column_index:
                if item != 0:
                    lower_flag = False
            
            if row_index>column_index:
                if item != 0:
                    upper_flag = False
                    
    if lower_flag:
        print("matrix type: Lower")
        #solve_lower(matrix)
            
    if upper_flag:
        print("matrix type: Upper")
        #solve_upper
        
    if lower_flag and upper_flag:
        print("matrix type: Diagonal")
        

matrix = read_txt("./demofile.txt")
print(matrix.shape)

check_triangularity(matrix)


['2,0,0,0', '2,3,0,0', '1,2,3,0', '3,4,5,6', '-1', '']
[[2 0 0 0]
 [2 3 0 0]
 [1 2 3 0]
 [3 4 5 6]]
(4, 4)
[2 0 0 0]
[2 3 0 0]
[1 2 3 0]
[3 4 5 6]
matrix type: Lower
